/**  
 - ACL (Access Control List), o Lista de Control de Acceso.
 -es un modelo para controlar qué usuarios o roles tienen permiso para realizar qué acciones sobre ciertos recursos. 
 
 */
export const ACL = {
  "/config/encargo": {
    GET: [
      "Dashboard",
      "Produccion",
      "Productor",
      "Empaque",
      "Recepcion",
      "Gerente",
      "Corte",
      "Fritura",
      "Alistamiento",
      "Cuartos",
    ],
    POST: ["Dashboard", "Productor"],
    PUT: ["Dashboard", "Productor"],
    DELETE: ["Produccion", "Productor"],
  },
  "/data/produccion": {
    GET: ["Gerente", "Dashboard", "Produccion", "Productor"],
    POST: ["Dashboard", "Productor"],
    PUT: ["Dashboard", "Productor"],
    DELETE: ["Produccion", "Productor"],
  },
  "/data/usuarios": {
    GET: ["Gerente", "RRHH", "Dashboard", "Produccion", "Productor"],
    POST: ["Dashboard", "Productor"],
    PUT: ["RRHH", "Dashboard", "Productor"],
    DELETE: ["Dashboard", "RRHH"],
  },
  "/data/empleados": {
    GET: [
      "Gerente",
      "RRHH",
      "Dashboard",
      "Produccion",
      "Productor",
      "Empaque",
      "Recepcion",
      "Corte",
      "Fritura",
      "Alistamiento",
      "Cuartos",
    ],
    POST: ["RRHH", "Dashboard", "Productor"],
    PUT: ["RRHH", "Dashboard", "Productor"],
    DELETE: ["Dashboard", "RRHH"],
  },
  "/data/historial": {
    GET: ["Gerente", "RRHH", "Dashboard", "Productor"],
    POST: ["Gerente", "RRHH", "Productor", "Dashboard"],
    PUT: ["Gerente", "RRHH", "Productor", "Dashboard"],
    DELETE: ["Gerente", "RRHH", "Productor", "Dashboard"],
  },
  "/data/dashboard": {
    GET: ["Gerente", "RRHH", "Dashboard", "Productor"],
  },
  "/data/rol": {
    GET: ["Gerente", "RRHH", "Productor", "Dashboard", "Produccion"],
    POST: ["RRHH", "Dashboard", "Gerente", "Productor"],
    PUT: ["RRHH", "Dashboard", "Gerente", "Productor"],
    DELETE: ["Dashboard", "Productor", "Gerente"],
  },
  "/data/referencias": {
    GET: [
      "Gerente",
      "Productor",
      "Dashboard",
      "Produccion",
      "Fritura",
      "Corte",
      "Empaque",
    ],
    POST: ["Gerente", "Dashboard", "Productor"],
    PUT: ["Gerente", "Dashboard", "Productor"],
    DELETE: ["Gerente", "Productor", "Dashboard"],
  },
  "/data/cliente": {
    GET: ["Gerente", "RRHH", "Dashboard"],
    POST: ["RRHH", "Gerente", "Dashboard"],
    PUT: ["RRHH", "Gerente", "Dashboard"],
    DELETE: ["Dashboard", "Gerente", "RRHH"],
  },
  "/data/proveedor": {
    GET: [
      "Gerente",
      "RRHH",
      "Dashboard",
      "Produccion",
      "Productor",
      "Recepcion",
    ],
    POST: ["RRHH", "Gerente", "Dashboard", "Productor"],
    PUT: ["RRHH", "Gerente", "Dashboard", "Productor"],
    DELETE: ["Dashboard", "Gerente"],
  },
  "/data/proveedorInsumos": {
    GET: ["Gerente", "RRHH", "Dashboard", "Productor"],
    POST: ["RRHH", "Gerente", "Dashboard", "Productor"],
    PUT: ["RRHH", "Gerente", "Dashboard", "Productor"],
    DELETE: ["Dashboard", "Gerente", "Productor"],
  },
  "/data/cuarto": {
    GET: ["Gerente", "RRHH", "Dashboard", "Produccion", "Productor", "Cuartos"],
    POST: ["RRHH", "Gerente", "Productor", "Dashboard"],
    PUT: ["RRHH", "Productor", "Dashboard"],
    DELETE: ["Dashboard"],
  },
  "/data/encargo": {
    GET: [
      "Gerente",
      "RRHH",
      "Dashboard",
      "Productor",
      "Empaque",
      "Recepcion",
      "Fritura",
      "Alistammiento",
    ],
    POST: ["RRHH", "Dashboard"],
    PUT: ["RRHH", "Dashboard"],
    DELETE: ["Dashboard", "RRHH", "Dashboard"],
  },
  "/data/produccion": {
    GET: ["Gerente", "RRHH", "Dashboard", "Productor"],
    POST: ["Productor", "Dashboard"],
    PUT: ["Productor", "Dashboard"],
    DELETE: ["Dashboard", "Productor", "Dashboard"],
  },
  "/data/recepcion": {
    GET: ["Gerente", "Productor", "Recepcion", "Produccion", "Dashboard", "Alistamiento", "Corte", "Fritura"],
    POST: ["Recepcion", "Produccion"],
    PUT: ["Productor", "Produccion"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/recepcionop": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard"],
    POST: ["Recepcion", "Produccion"],
    PUT: ["Produccion", "Dashboard", "Productor", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/alistamiento": {
    GET: ["Gerente", "Productor", "Corte", "Produccion", "Dashboard", "Alistamiento"],
    POST: ["Alistammiento", "Produccion", "Productor"],
    PUT: ["Produccion", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/corte": {
    GET: ["Gerente", "Productor", "Fritura", "Produccion", "Dashboard", "Corte"],
    POST: ["Corte", "Produccion"],
    PUT: ["Produccion", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/fritura": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard", "Empaque"],
    POST: ["Fritura", "Produccion"],
    PUT: ["Produccion", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/empaque": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard"],
    POST: ["Empaque", "Produccion"],
    PUT: ["Produccion", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/bodega": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard"],
    POST: ["Empaque", "Productor", "Produccion", "Dashboard"],
    PUT: ["Empaque", "Produccion", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/materia": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard"],
    POST: ["Gerente", "Productor", "Produccion", "Dashboard"],
    PUT: ["Gerente", "Produccion", "Dashboard", "Productor"],
    DELETE: ["Gerente", "Produccion", "Dashboard", "Productor"],
  },
  "/data/inventario": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard", "RRHH"],
    POST: ["Dashboard", "Produccion", "RRHH"],
    PUT: ["Produccion", "Dashboard", "Productor", "RRHH"],
    DELETE: ["Dashboard", "RRHH"],
  },
  "/data/insumos": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard", "RRHH"],
    POST: ["Dashboard", "Produccion", "RRHH", "Productor"],
    PUT: ["Dashboard", "Productor", "RRHH"],
    DELETE: ["Dashboard", "RRHH", "Productor"],
  },
  "/data/verificacion": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard", "Empaque"],
    POST: ["Empaque", "Produccion"],
    PUT: ["Produccion", "Empaque", "Dashboard", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/temperatura": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard"],
    POST: ["Cuartos", "Produccion"],
    PUT: ["Produccion", "Productor"],
    DELETE: ["Produccion", "Dashboard"],
  },
  "/data/lotes-fritura": {
    GET: ["Gerente", "Productor", "Produccion", "Dashboard", "Fritura"],
    POST: ["Fritura", "Produccion", "Gerente"],
    PUT: ["Produccion", "Dashboard", "Productor", "Fritura", "Gerente"],
    DELETE: ["Produccion", "Dashboard", "Gerente"],
  },
};

export default ACL;
